import type { KnowledgeGraph } from '../types/knowledgeGraph';

export const knowledgeGraph: KnowledgeGraph = {
  nodes: [
    { id: 'ds-linear', name: '线性表', subject: '数据结构', category: '线性结构', difficulty: 2, questionCount: 85, wrongCount: 22 },
    { id: 'ds-stack', name: '栈', subject: '数据结构', category: '线性结构', difficulty: 2, questionCount: 60, wrongCount: 15 },
    { id: 'ds-queue', name: '队列', subject: '数据结构', category: '线性结构', difficulty: 2, questionCount: 55, wrongCount: 12 },
    { id: 'ds-string', name: '串', subject: '数据结构', category: '线性结构', difficulty: 3, questionCount: 40, wrongCount: 18 },
    { id: 'ds-tree', name: '树与二叉树', subject: '数据结构', category: '树形结构', difficulty: 4, questionCount: 110, wrongCount: 45 },
    { id: 'ds-bst', name: '二叉搜索树', subject: '数据结构', category: '树形结构', difficulty: 4, questionCount: 50, wrongCount: 20 },
    { id: 'ds-avl', name: 'AVL树', subject: '数据结构', category: '树形结构', difficulty: 5, questionCount: 30, wrongCount: 16 },
    { id: 'ds-btree', name: 'B树与B+树', subject: '数据结构', category: '树形结构', difficulty: 5, questionCount: 35, wrongCount: 19 },
    { id: 'ds-graph', name: '图', subject: '数据结构', category: '图结构', difficulty: 5, questionCount: 95, wrongCount: 42 },
    { id: 'ds-sort', name: '排序', subject: '数据结构', category: '算法', difficulty: 4, questionCount: 120, wrongCount: 50 },
    { id: 'ds-search', name: '查找', subject: '数据结构', category: '算法', difficulty: 3, questionCount: 70, wrongCount: 25 },
    { id: 'ds-hash', name: '散列表', subject: '数据结构', category: '算法', difficulty: 3, questionCount: 45, wrongCount: 18 },
    { id: 'ds-heap', name: '堆', subject: '数据结构', category: '树形结构', difficulty: 3, questionCount: 35, wrongCount: 14 },
    { id: 'ds-recursion', name: '递归与分治', subject: '数据结构', category: '算法', difficulty: 3, questionCount: 50, wrongCount: 22 },
    { id: 'ds-greedy', name: '贪心与动态规划', subject: '数据结构', category: '算法', difficulty: 5, questionCount: 65, wrongCount: 38 },

    { id: 'os-intro', name: '操作系统概述', subject: '操作系统', category: '基础概念', difficulty: 1, questionCount: 30, wrongCount: 5 },
    { id: 'os-process', name: '进程管理', subject: '操作系统', category: '处理机管理', difficulty: 4, questionCount: 100, wrongCount: 40 },
    { id: 'os-thread', name: '线程与并发', subject: '操作系统', category: '处理机管理', difficulty: 4, questionCount: 80, wrongCount: 35 },
    { id: 'os-schedule', name: '处理机调度', subject: '操作系统', category: '处理机管理', difficulty: 4, questionCount: 65, wrongCount: 28 },
    { id: 'os-synch', name: '同步与互斥', subject: '操作系统', category: '处理机管理', difficulty: 5, questionCount: 75, wrongCount: 38 },
    { id: 'os-deadlock', name: '死锁', subject: '操作系统', category: '处理机管理', difficulty: 4, questionCount: 45, wrongCount: 20 },
    { id: 'os-memory', name: '内存管理', subject: '操作系统', category: '存储管理', difficulty: 4, questionCount: 90, wrongCount: 38 },
    { id: 'os-virtual', name: '虚拟内存', subject: '操作系统', category: '存储管理', difficulty: 5, questionCount: 55, wrongCount: 28 },
    { id: 'os-file', name: '文件系统', subject: '操作系统', category: '文件管理', difficulty: 3, questionCount: 50, wrongCount: 18 },
    { id: 'os-io', name: 'I/O管理', subject: '操作系统', category: '设备管理', difficulty: 3, questionCount: 40, wrongCount: 15 },
    { id: 'os-disk', name: '磁盘与存储', subject: '操作系统', category: '设备管理', difficulty: 3, questionCount: 35, wrongCount: 14 },
    { id: 'os-protect', name: '保护与安全', subject: '操作系统', category: '基础概念', difficulty: 2, questionCount: 25, wrongCount: 8 },

    { id: 'co-data', name: '数据表示', subject: '计算机组成原理', category: '数据系统', difficulty: 3, questionCount: 60, wrongCount: 22 },
    { id: 'co-alu', name: '运算器与ALU', subject: '计算机组成原理', category: '数据系统', difficulty: 4, questionCount: 50, wrongCount: 24 },
    { id: 'co-store', name: '存储系统', subject: '计算机组成原理', category: '存储层次', difficulty: 4, questionCount: 75, wrongCount: 32 },
    { id: 'co-cache', name: '高速缓存', subject: '计算机组成原理', category: '存储层次', difficulty: 5, questionCount: 55, wrongCount: 28 },
    { id: 'co-instr', name: '指令系统', subject: '计算机组成原理', category: '指令系统', difficulty: 4, questionCount: 65, wrongCount: 30 },
    { id: 'co-cpu', name: 'CPU结构与功能', subject: '计算机组成原理', category: '中央处理器', difficulty: 5, questionCount: 80, wrongCount: 38 },
    { id: 'co-pipeline', name: '流水线技术', subject: '计算机组成原理', category: '中央处理器', difficulty: 5, questionCount: 45, wrongCount: 25 },
    { id: 'co-bus', name: '总线系统', subject: '计算机组成原理', category: '系统互联', difficulty: 3, questionCount: 35, wrongCount: 12 },
    { id: 'co-io', name: '输入输出系统', subject: '计算机组成原理', category: '系统互联', difficulty: 3, questionCount: 40, wrongCount: 15 },
    { id: 'co-interrupt', name: '中断系统', subject: '计算机组成原理', category: '系统互联', difficulty: 4, questionCount: 35, wrongCount: 16 },
    { id: 'co-redundancy', name: '冗余与校验', subject: '计算机组成原理', category: '数据系统', difficulty: 3, questionCount: 30, wrongCount: 10 },
    { id: 'co-risc', name: 'RISC与CISC', subject: '计算机组成原理', category: '指令系统', difficulty: 3, questionCount: 25, wrongCount: 9 },

    { id: 'cn-phy', name: '物理层', subject: '计算机网络', category: '网络层次', difficulty: 2, questionCount: 35, wrongCount: 10 },
    { id: 'cn-dll', name: '数据链路层', subject: '计算机网络', category: '网络层次', difficulty: 3, questionCount: 60, wrongCount: 22 },
    { id: 'cn-mac', name: '介质访问控制', subject: '计算机网络', category: '网络层次', difficulty: 3, questionCount: 40, wrongCount: 16 },
    { id: 'cn-switch', name: '交换机与局域网', subject: '计算机网络', category: '网络层次', difficulty: 3, questionCount: 35, wrongCount: 12 },
    { id: 'cn-net', name: '网络层', subject: '计算机网络', category: '网络层次', difficulty: 4, questionCount: 90, wrongCount: 38 },
    { id: 'cn-ip', name: 'IP协议', subject: '计算机网络', category: '网络层次', difficulty: 4, questionCount: 75, wrongCount: 32 },
    { id: 'cn-route', name: '路由算法', subject: '计算机网络', category: '网络层次', difficulty: 5, questionCount: 55, wrongCount: 28 },
    { id: 'cn-trans', name: '传输层', subject: '计算机网络', category: '网络层次', difficulty: 4, questionCount: 85, wrongCount: 36 },
    { id: 'cn-tcp', name: 'TCP协议', subject: '计算机网络', category: '网络层次', difficulty: 5, questionCount: 70, wrongCount: 32 },
    { id: 'cn-udp', name: 'UDP协议', subject: '计算机网络', category: '网络层次', difficulty: 3, questionCount: 30, wrongCount: 10 },
    { id: 'cn-app', name: '应用层', subject: '计算机网络', category: '网络层次', difficulty: 3, questionCount: 55, wrongCount: 18 },
    { id: 'cn-sec', name: '网络安全', subject: '计算机网络', category: '安全基础', difficulty: 3, questionCount: 40, wrongCount: 15 },
  ],

  edges: [
    { source: 'ds-linear', target: 'ds-stack', relationship: 'part_of', weight: 0.9 },
    { source: 'ds-linear', target: 'ds-queue', relationship: 'part_of', weight: 0.9 },
    { source: 'ds-linear', target: 'ds-string', relationship: 'related', weight: 0.6 },
    { source: 'ds-stack', target: 'ds-recursion', relationship: 'prerequisite', weight: 0.7 },
    { source: 'ds-tree', target: 'ds-bst', relationship: 'part_of', weight: 0.9 },
    { source: 'ds-bst', target: 'ds-avl', relationship: 'prerequisite', weight: 0.8 },
    { source: 'ds-tree', target: 'ds-btree', relationship: 'prerequisite', weight: 0.7 },
    { source: 'ds-tree', target: 'ds-heap', relationship: 'related', weight: 0.8 },
    { source: 'ds-graph', target: 'ds-sort', relationship: 'related', weight: 0.6 },
    { source: 'ds-search', target: 'ds-hash', relationship: 'related', weight: 0.7 },
    { source: 'ds-bst', target: 'ds-search', relationship: 'prerequisite', weight: 0.8 },
    { source: 'ds-recursion', target: 'ds-sort', relationship: 'related', weight: 0.6 },
    { source: 'ds-greedy', target: 'ds-sort', relationship: 'related', weight: 0.5 },
    { source: 'ds-heap', target: 'ds-sort', relationship: 'prerequisite', weight: 0.8 },
    { source: 'ds-graph', target: 'ds-search', relationship: 'related', weight: 0.5 },

    { source: 'os-intro', target: 'os-process', relationship: 'prerequisite', weight: 0.7 },
    { source: 'os-process', target: 'os-thread', relationship: 'prerequisite', weight: 0.9 },
    { source: 'os-process', target: 'os-schedule', relationship: 'prerequisite', weight: 0.8 },
    { source: 'os-schedule', target: 'os-deadlock', relationship: 'related', weight: 0.7 },
    { source: 'os-synch', target: 'os-deadlock', relationship: 'related', weight: 0.8 },
    { source: 'os-thread', target: 'os-synch', relationship: 'prerequisite', weight: 0.9 },
    { source: 'os-memory', target: 'os-virtual', relationship: 'prerequisite', weight: 0.9 },
    { source: 'os-file', target: 'os-io', relationship: 'related', weight: 0.7 },
    { source: 'os-io', target: 'os-disk', relationship: 'part_of', weight: 0.8 },

    { source: 'co-data', target: 'co-alu', relationship: 'prerequisite', weight: 0.8 },
    { source: 'co-store', target: 'co-cache', relationship: 'part_of', weight: 0.9 },
    { source: 'co-instr', target: 'co-cpu', relationship: 'prerequisite', weight: 0.9 },
    { source: 'co-cpu', target: 'co-pipeline', relationship: 'related', weight: 0.8 },
    { source: 'co-bus', target: 'co-io', relationship: 'related', weight: 0.7 },
    { source: 'co-io', target: 'co-interrupt', relationship: 'related', weight: 0.8 },
    { source: 'co-instr', target: 'co-risc', relationship: 'related', weight: 0.7 },
    { source: 'co-data', target: 'co-redundancy', relationship: 'related', weight: 0.6 },

    { source: 'cn-phy', target: 'cn-dll', relationship: 'prerequisite', weight: 0.9 },
    { source: 'cn-dll', target: 'cn-mac', relationship: 'prerequisite', weight: 0.8 },
    { source: 'cn-dll', target: 'cn-switch', relationship: 'related', weight: 0.8 },
    { source: 'cn-mac', target: 'cn-switch', relationship: 'prerequisite', weight: 0.7 },
    { source: 'cn-dll', target: 'cn-net', relationship: 'prerequisite', weight: 0.9 },
    { source: 'cn-net', target: 'cn-ip', relationship: 'part_of', weight: 0.9 },
    { source: 'cn-ip', target: 'cn-route', relationship: 'related', weight: 0.8 },
    { source: 'cn-net', target: 'cn-trans', relationship: 'prerequisite', weight: 0.9 },
    { source: 'cn-trans', target: 'cn-tcp', relationship: 'part_of', weight: 0.9 },
    { source: 'cn-trans', target: 'cn-udp', relationship: 'part_of', weight: 0.8 },
    { source: 'cn-trans', target: 'cn-app', relationship: 'prerequisite', weight: 0.9 },
    { source: 'cn-app', target: 'cn-sec', relationship: 'related', weight: 0.6 },

    { source: 'ds-graph', target: 'cn-route', relationship: 'related', weight: 0.6 },
    { source: 'os-process', target: 'co-cpu', relationship: 'related', weight: 0.7 },
    { source: 'os-schedule', target: 'co-pipeline', relationship: 'related', weight: 0.5 },
    { source: 'os-memory', target: 'co-cache', relationship: 'related', weight: 0.7 },
    { source: 'ds-hash', target: 'cn-dll', relationship: 'related', weight: 0.4 },
    { source: 'os-io', target: 'co-io', relationship: 'related', weight: 0.6 },
  ],
};
