import type {
  Subject,
  Question,
  WrongQuestion,
  ReviewTask,
  StudyRecord,
  DashboardStats,
  AnalyticsData,
} from '../types';

export const mockSubjects: Subject[] = [
  {
    id: 'sub-1',
    name: '数据结构',
    code: 'CS408-DS',
    questionCount: 200,
    correctRate: 0.78,
    description: '包含线性表、树、图、排序、查找等核心数据结构与算法',
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'sub-2',
    name: '操作系统',
    code: 'CS408-OS',
    questionCount: 180,
    correctRate: 0.72,
    description: '进程管理、内存管理、文件系统、I/O系统等操作系统核心知识',
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'sub-3',
    name: '计算机组成原理',
    code: 'CS408-CO',
    questionCount: 160,
    correctRate: 0.68,
    description: 'CPU结构、存储系统、总线与I/O、指令系统等计算机硬件基础',
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'sub-4',
    name: '计算机网络',
    code: 'CS408-CN',
    questionCount: 150,
    correctRate: 0.81,
    description: 'OSI七层模型、TCP/IP协议族、网络安全与应用层协议',
    createdAt: '2025-09-01T00:00:00.000Z',
  },
];

// Knowledge points (subset for reference)
export const knowledgePoints = {
  'sub-1': [
    { id: 'kp-ds-1', title: '线性表', level: 1 },
    { id: 'kp-ds-2', title: '栈和队列', level: 1 },
    { id: 'kp-ds-3', title: '树与二叉树', level: 1 },
    { id: 'kp-ds-4', title: '图', level: 1 },
    { id: 'kp-ds-5', title: '排序算法', level: 1 },
    { id: 'kp-ds-6', title: '查找算法', level: 1 },
  ],
  'sub-2': [
    { id: 'kp-os-1', title: '进程管理', level: 1 },
    { id: 'kp-os-2', title: '内存管理', level: 1 },
    { id: 'kp-os-3', title: '文件系统', level: 1 },
    { id: 'kp-os-4', title: 'I/O管理', level: 1 },
  ],
  'sub-3': [
    { id: 'kp-co-1', title: 'CPU结构与功能', level: 1 },
    { id: 'kp-co-2', title: '存储系统', level: 1 },
    { id: 'kp-co-3', title: '指令系统', level: 1 },
    { id: 'kp-co-4', title: '总线与I/O', level: 1 },
  ],
  'sub-4': [
    { id: 'kp-cn-1', title: '物理层与数据链路层', level: 1 },
    { id: 'kp-cn-2', title: '网络层', level: 1 },
    { id: 'kp-cn-3', title: '传输层', level: 1 },
    { id: 'kp-cn-4', title: '应用层', level: 1 },
  ],
};

export const mockQuestions: Question[] = [
  // 数据结构
  {
    id: 'q-1',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-3',
    difficulty: 'medium',
    type: 'choice',
    content: '在一棵具有n个结点的完全二叉树中，树的深度为:',
    options: ['A. floor(log2(n))', 'B. floor(log2(n)) + 1', 'C. ceil(log2(n))', 'D. ceil(log2(n)) + 1'],
    correctAnswer: 'B',
    analysis: '完全二叉树的深度为floor(log2(n)) + 1。根结点在第1层，深度为1时有1个结点，深度为d时最多有2^d - 1个结点。',
    tags: ['二叉树', '完全二叉树', '深度'],
    createdAt: '2025-10-15T08:00:00.000Z',
  },
  {
    id: 'q-2',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-5',
    difficulty: 'hard',
    type: 'choice',
    content: '快速排序在下列哪种情况下效率最差:',
    options: ['A. 数据已基本有序', 'B. 数据完全随机', 'C. 数据逆序排列', 'D. 数据全部相同'],
    correctAnswer: 'A',
    analysis: '当数据已基本有序时，快速排序退化为O(n^2)，因为每次划分都极不平衡。实际上C和D也导致差的划分，但A是最典型的情况。',
    tags: ['排序', '快速排序', '时间复杂度'],
    createdAt: '2025-10-16T08:00:00.000Z',
  },
  {
    id: 'q-3',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-2',
    difficulty: 'easy',
    type: 'choice',
    content: '栈的特点是:',
    options: ['A. 先进先出', 'B. 先进后出', 'C. 随机存取', 'D. 以上都不对'],
    correctAnswer: 'B',
    analysis: '栈是一种后进先出(LIFO)的数据结构，只能在栈顶进行插入和删除操作。',
    tags: ['栈', '基本概念'],
    createdAt: '2025-10-17T08:00:00.000Z',
  },
  {
    id: 'q-4',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-4',
    difficulty: 'medium',
    type: 'choice',
    content: '对有n个顶点的无向连通图，至少需要多少条边:',
    options: ['A. n', 'B. n-1', 'C. n+1', 'D. n(n-1)/2'],
    correctAnswer: 'B',
    analysis: 'n个顶点的连通图至少需要n-1条边，这构成一棵生成树。少于n-1条边则图不连通。',
    tags: ['图', '连通图', '生成树'],
    createdAt: '2025-10-18T08:00:00.000Z',
  },
  {
    id: 'q-5',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-6',
    difficulty: 'medium',
    type: 'choice',
    content: '二分查找要求被查找的表必须满足:',
    options: ['A. 链表存储', 'B. 有序', 'C. 顺序存储', 'D. 有序且顺序存储'],
    correctAnswer: 'D',
    analysis: '二分查找要求数据有序且采用顺序存储（如数组），因为需要通过下标随机访问中间元素。',
    tags: ['查找', '二分查找'],
    createdAt: '2025-10-19T08:00:00.000Z',
  },
  {
    id: 'q-6',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-1',
    difficulty: 'easy',
    type: 'choice',
    content: '单链表中，增加头结点的目的是:',
    options: ['A. 使单链表至少有一个结点', 'B. 标识链表中首个位置的元素结点', 'C. 方便运算的实现', 'D. 说明单链表是线性的'],
    correctAnswer: 'C',
    analysis: '头结点的引入使得在链表的第一个位置进行插入、删除操作与其他位置一致，无需特殊处理，简化了运算实现。',
    tags: ['线性表', '单链表', '头结点'],
    createdAt: '2025-10-20T08:00:00.000Z',
  },
  // 操作系统
  {
    id: 'q-7',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-1',
    difficulty: 'medium',
    type: 'choice',
    content: '进程从阻塞状态变为就绪状态的原因是:',
    options: ['A. 时间片用完', 'B. 等待的事件发生', 'C. 进程调度程序选中该进程', 'D. 进程主动放弃CPU'],
    correctAnswer: 'B',
    analysis: '进程在阻塞状态等待某个事件（如I/O完成），当该事件发生时，进程从阻塞状态转入就绪状态，等待CPU调度。',
    tags: ['进程管理', '进程状态'],
    createdAt: '2025-10-15T09:00:00.000Z',
  },
  {
    id: 'q-8',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-2',
    difficulty: 'hard',
    type: 'choice',
    content: '在请求分页系统中，若页面置换算法选择不当，会产生哪种现象:',
    options: ['A. 中断', 'B. 抖动', 'C. 死锁', 'D. 碎片'],
    correctAnswer: 'B',
    analysis: '抖动(thrashing)是指页面频繁换入换出的现象，通常因分配给进程的物理页帧不足或置换算法不当导致。',
    tags: ['内存管理', '页面置换', '抖动'],
    createdAt: '2025-10-16T09:00:00.000Z',
  },
  {
    id: 'q-9',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-1',
    difficulty: 'easy',
    type: 'choice',
    content: '操作系统的核心作用是:',
    options: ['A. 编译程序', 'B. 管理和分配计算机资源', 'C. 文字处理', 'D. 数据库管理'],
    correctAnswer: 'B',
    analysis: '操作系统是管理计算机硬件与软件资源的系统软件，负责资源的分配、调度和管理。',
    tags: ['操作系统', '基本概念'],
    createdAt: '2025-10-17T09:00:00.000Z',
  },
  {
    id: 'q-10',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-3',
    difficulty: 'medium',
    type: 'choice',
    content: '文件系统中，位示图法用于:',
    options: ['A. 文件保护', 'B. 磁盘空间管理', 'C. 目录管理', 'D. 文件存取'],
    correctAnswer: 'B',
    analysis: '位示图(bitmap)用每一位表示一个磁盘块的使用状态，0表示空闲，1表示已分配，是磁盘空间管理的常用方法。',
    tags: ['文件系统', '磁盘管理'],
    createdAt: '2025-10-18T09:00:00.000Z',
  },
  {
    id: 'q-11',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-1',
    difficulty: 'medium',
    type: 'choice',
    content: '银行家算法用于解决:',
    options: ['A. 页面置换', 'B. 进程同步', 'C. 死锁避免', 'D. 作业调度'],
    correctAnswer: 'C',
    analysis: '银行家算法是经典的死锁避免算法，通过在资源分配前检查系统是否处于安全状态来避免死锁的发生。',
    tags: ['进程管理', '死锁', '银行家算法'],
    createdAt: '2025-10-19T09:00:00.000Z',
  },
  // 计算机组成原理
  {
    id: 'q-12',
    subjectId: 'sub-3',
    knowledgePointId: 'kp-co-1',
    difficulty: 'medium',
    type: 'choice',
    content: 'CPU中，程序计数器(PC)存放的是:',
    options: ['A. 当前指令的地址', 'B. 下一条要执行的指令地址', 'C. 当前指令的操作码', 'D. 栈顶地址'],
    correctAnswer: 'B',
    analysis: '程序计数器(PC)保存的是下一条将要执行的指令的内存地址，CPU根据PC的值取指令执行。',
    tags: ['CPU', '程序计数器'],
    createdAt: '2025-10-15T10:00:00.000Z',
  },
  {
    id: 'q-13',
    subjectId: 'sub-3',
    knowledgePointId: 'kp-co-2',
    difficulty: 'hard',
    type: 'choice',
    content: '在Cache-主存映射方式中，组相联映射是哪两种方式的折中:',
    options: ['A. 全相联和直接映射', 'B. 全相联和间接映射', 'C. 直接映射和间接映射', 'D. 以上都不是'],
    correctAnswer: 'A',
    analysis: '组相联映射将Cache分为若干组，组间采用直接映射，组内采用全相联映射，是两者的折中方案。',
    tags: ['Cache', '映射方式'],
    createdAt: '2025-10-16T10:00:00.000Z',
  },
  {
    id: 'q-14',
    subjectId: 'sub-3',
    knowledgePointId: 'kp-co-3',
    difficulty: 'easy',
    type: 'choice',
    content: 'RISC(精简指令集计算机)的特点不包括:',
    options: ['A. 指令数量少', 'B. 指令长度固定', 'C. 寻址方式多', 'D. 采用硬布线控制'],
    correctAnswer: 'C',
    analysis: 'RISC的特点包括：指令少、指令长度固定、寻址方式少、采用硬布线控制等。寻址方式多是CISC的特点。',
    tags: ['指令系统', 'RISC'],
    createdAt: '2025-10-17T10:00:00.000Z',
  },
  {
    id: 'q-15',
    subjectId: 'sub-3',
    knowledgePointId: 'kp-co-4',
    difficulty: 'medium',
    type: 'choice',
    content: '总线的带宽是指:',
    options: ['A. 总线的位宽', 'B. 总线的工作频率', 'C. 单位时间内总线可传输的数据量', 'D. 总线的物理长度'],
    correctAnswer: 'C',
    analysis: '总线带宽是单位时间内总线传输数据的能力，等于总线位宽乘以工作频率（考虑有效传输比率）。',
    tags: ['总线', '带宽'],
    createdAt: '2025-10-18T10:00:00.000Z',
  },
  // 计算机网络
  {
    id: 'q-16',
    subjectId: 'sub-4',
    knowledgePointId: 'kp-cn-3',
    difficulty: 'medium',
    type: 'choice',
    content: 'TCP建立连接需要几次握手:',
    options: ['A. 一次', 'B. 两次', 'C. 三次', 'D. 四次'],
    correctAnswer: 'C',
    analysis: 'TCP建立连接需要三次握手：客户端发送SYN，服务器回复SYN+ACK，客户端再发送ACK确认。',
    tags: ['TCP', '三次握手'],
    createdAt: '2025-10-15T11:00:00.000Z',
  },
  {
    id: 'q-17',
    subjectId: 'sub-4',
    knowledgePointId: 'kp-cn-2',
    difficulty: 'easy',
    type: 'choice',
    content: 'IP地址127.0.0.1属于:',
    options: ['A. A类地址', 'B. B类地址', 'C. C类地址', 'D. 环回地址'],
    correctAnswer: 'D',
    analysis: '127.0.0.1是环回地址（loopback），用于本机测试，发送到该地址的数据包不会离开主机。',
    tags: ['IP地址', '环回地址'],
    createdAt: '2025-10-16T11:00:00.000Z',
  },
  {
    id: 'q-18',
    subjectId: 'sub-4',
    knowledgePointId: 'kp-cn-1',
    difficulty: 'hard',
    type: 'choice',
    content: '以太网使用的介质访问控制方法是:',
    options: ['A. 令牌传递', 'B. CSMA/CD', 'C. FDDI', 'D. TDMA'],
    correctAnswer: 'B',
    analysis: '以太网采用CSMA/CD(Carrier Sense Multiple Access with Collision Detection)作为介质访问控制方法。',
    tags: ['以太网', 'CSMA/CD'],
    createdAt: '2025-10-17T11:00:00.000Z',
  },
  {
    id: 'q-19',
    subjectId: 'sub-4',
    knowledgePointId: 'kp-cn-4',
    difficulty: 'medium',
    type: 'choice',
    content: 'HTTP协议默认使用的端口号是:',
    options: ['A. 21', 'B. 25', 'C. 80', 'D. 443'],
    correctAnswer: 'C',
    analysis: 'HTTP默认端口为80，HTTPS默认端口为443，FTP默认端口为21，SMTP默认端口为25。',
    tags: ['HTTP', '端口号'],
    createdAt: '2025-10-18T11:00:00.000Z',
  },
  {
    id: 'q-20',
    subjectId: 'sub-4',
    knowledgePointId: 'kp-cn-3',
    difficulty: 'easy',
    type: 'choice',
    content: 'UDP协议的特点是:',
    options: ['A. 面向连接', 'B. 可靠传输', 'C. 无连接、不可靠', 'D. 流量控制'],
    correctAnswer: 'C',
    analysis: 'UDP是无连接的传输层协议，不保证可靠传输，没有拥塞控制和流量控制机制，适合实时应用。',
    tags: ['UDP', '传输层'],
    createdAt: '2025-10-19T11:00:00.000Z',
  },
  {
    id: 'q-21',
    subjectId: 'sub-1',
    knowledgePointId: 'kp-ds-3',
    difficulty: 'hard',
    type: 'choice',
    content: '哈夫曼树的带权路径长度(WPL)是:',
    options: ['A. 所有结点权值之和', 'B. 所有叶子结点权值乘以路径长度之和', 'C. 树的深度乘以权值', 'D. 结点数乘以深度'],
    correctAnswer: 'B',
    analysis: 'WPL = sum(wi * li)，其中wi是第i个叶子结点的权值，li是从根到该叶子结点的路径长度。哈夫曼树使WPL最小。',
    tags: ['哈夫曼树', 'WPL'],
    createdAt: '2025-10-21T08:00:00.000Z',
  },
  {
    id: 'q-22',
    subjectId: 'sub-2',
    knowledgePointId: 'kp-os-4',
    difficulty: 'easy',
    type: 'choice',
    content: 'DMA方式中，数据传输的基本单位是:',
    options: ['A. 位', 'B. 字节', 'C. 数据块', 'D. 字'],
    correctAnswer: 'C',
    analysis: 'DMA(直接存储器访问)以数据块为单位传输数据，不需要CPU逐字节处理，提高了I/O效率。',
    tags: ['I/O管理', 'DMA'],
    createdAt: '2025-10-21T09:00:00.000Z',
  },
];

export const mockWrongQuestions: WrongQuestion[] = [
  {
    id: 'wq-1',
    questionId: 'q-1',
    question: mockQuestions.find((q) => q.id === 'q-1')!,
    status: 'NEW',
    wrongCount: 2,
    lastWrongAt: '2025-11-01T14:30:00.000Z',
    nextReviewAt: null,
    reviewCount: 0,
    createdAt: '2025-11-01T14:30:00.000Z',
  },
  {
    id: 'wq-2',
    questionId: 'q-2',
    question: mockQuestions.find((q) => q.id === 'q-2')!,
    status: 'REVIEWING',
    wrongCount: 3,
    lastWrongAt: '2025-11-03T10:00:00.000Z',
    nextReviewAt: '2025-11-10T10:00:00.000Z',
    reviewCount: 1,
    createdAt: '2025-10-28T16:00:00.000Z',
  },
  {
    id: 'wq-3',
    questionId: 'q-8',
    question: mockQuestions.find((q) => q.id === 'q-8')!,
    status: 'NEW',
    wrongCount: 1,
    lastWrongAt: '2025-11-02T09:15:00.000Z',
    nextReviewAt: null,
    reviewCount: 0,
    createdAt: '2025-11-02T09:15:00.000Z',
  },
  {
    id: 'wq-4',
    questionId: 'q-13',
    question: mockQuestions.find((q) => q.id === 'q-13')!,
    status: 'REVIEWING',
    wrongCount: 2,
    lastWrongAt: '2025-11-04T11:20:00.000Z',
    nextReviewAt: '2025-11-08T11:20:00.000Z',
    reviewCount: 2,
    createdAt: '2025-10-30T08:00:00.000Z',
  },
  {
    id: 'wq-5',
    questionId: 'q-15',
    question: mockQuestions.find((q) => q.id === 'q-15')!,
    status: 'MASTERED',
    wrongCount: 4,
    lastWrongAt: '2025-10-25T15:00:00.000Z',
    nextReviewAt: null,
    reviewCount: 3,
    createdAt: '2025-10-20T10:00:00.000Z',
  },
  {
    id: 'wq-6',
    questionId: 'q-18',
    question: mockQuestions.find((q) => q.id === 'q-18')!,
    status: 'NEW',
    wrongCount: 1,
    lastWrongAt: '2025-11-05T13:45:00.000Z',
    nextReviewAt: null,
    reviewCount: 0,
    createdAt: '2025-11-05T13:45:00.000Z',
  },
  {
    id: 'wq-7',
    questionId: 'q-5',
    question: mockQuestions.find((q) => q.id === 'q-5')!,
    status: 'REVIEWING',
    wrongCount: 2,
    lastWrongAt: '2025-11-03T16:30:00.000Z',
    nextReviewAt: '2025-11-09T16:30:00.000Z',
    reviewCount: 1,
    createdAt: '2025-10-29T14:00:00.000Z',
  },
  {
    id: 'wq-8',
    questionId: 'q-21',
    question: mockQuestions.find((q) => q.id === 'q-21')!,
    status: 'NEW',
    wrongCount: 1,
    lastWrongAt: '2025-11-05T08:20:00.000Z',
    nextReviewAt: null,
    reviewCount: 0,
    createdAt: '2025-11-05T08:20:00.000Z',
  },
];

export const mockReviewTasks: ReviewTask[] = [
  {
    id: 'rt-1',
    wrongQuestionId: 'wq-2',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-2')!,
    dueDate: '2025-11-07',
    completed: false,
    completedAt: null,
    result: null,
  },
  {
    id: 'rt-2',
    wrongQuestionId: 'wq-4',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-4')!,
    dueDate: '2025-11-07',
    completed: false,
    completedAt: null,
    result: null,
  },
  {
    id: 'rt-3',
    wrongQuestionId: 'wq-7',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-7')!,
    dueDate: '2025-11-07',
    completed: false,
    completedAt: null,
    result: null,
  },
  {
    id: 'rt-4',
    wrongQuestionId: 'wq-1',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-1')!,
    dueDate: '2025-11-08',
    completed: false,
    completedAt: null,
    result: null,
  },
  {
    id: 'rt-5',
    wrongQuestionId: 'wq-3',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-3')!,
    dueDate: '2025-11-09',
    completed: false,
    completedAt: null,
    result: null,
  },
  {
    id: 'rt-6',
    wrongQuestionId: 'wq-5',
    wrongQuestion: mockWrongQuestions.find((w) => w.id === 'wq-5')!,
    dueDate: '2025-11-06',
    completed: true,
    completedAt: '2025-11-06T09:00:00.000Z',
    result: 'remembered',
  },
];

export const mockStudyRecords: StudyRecord[] = [
  { id: 'sr-1', date: '2025-10-23', subjectId: 'sub-1', subjectName: '数据结构', questionsDone: 15, correctCount: 12, wrongCount: 3, duration: 45 },
  { id: 'sr-2', date: '2025-10-24', subjectId: 'sub-2', subjectName: '操作系统', questionsDone: 12, correctCount: 8, wrongCount: 4, duration: 40 },
  { id: 'sr-3', date: '2025-10-25', subjectId: 'sub-1', subjectName: '数据结构', questionsDone: 20, correctCount: 16, wrongCount: 4, duration: 55 },
  { id: 'sr-4', date: '2025-10-25', subjectId: 'sub-3', subjectName: '计算机组成原理', questionsDone: 10, correctCount: 6, wrongCount: 4, duration: 35 },
  { id: 'sr-5', date: '2025-10-26', subjectId: 'sub-4', subjectName: '计算机网络', questionsDone: 18, correctCount: 15, wrongCount: 3, duration: 50 },
  { id: 'sr-6', date: '2025-10-27', subjectId: 'sub-1', subjectName: '数据结构', questionsDone: 22, correctCount: 18, wrongCount: 4, duration: 60 },
  { id: 'sr-7', date: '2025-10-28', subjectId: 'sub-2', subjectName: '操作系统', questionsDone: 16, correctCount: 11, wrongCount: 5, duration: 48 },
  { id: 'sr-8', date: '2025-10-29', subjectId: 'sub-3', subjectName: '计算机组成原理', questionsDone: 14, correctCount: 9, wrongCount: 5, duration: 42 },
  { id: 'sr-9', date: '2025-10-30', subjectId: 'sub-4', subjectName: '计算机网络', questionsDone: 20, correctCount: 17, wrongCount: 3, duration: 52 },
  { id: 'sr-10', date: '2025-10-31', subjectId: 'sub-1', subjectName: '数据结构', questionsDone: 25, correctCount: 20, wrongCount: 5, duration: 65 },
  { id: 'sr-11', date: '2025-11-01', subjectId: 'sub-2', subjectName: '操作系统', questionsDone: 18, correctCount: 13, wrongCount: 5, duration: 50 },
  { id: 'sr-12', date: '2025-11-02', subjectId: 'sub-1', subjectName: '数据结构', questionsDone: 30, correctCount: 24, wrongCount: 6, duration: 70 },
  { id: 'sr-13', date: '2025-11-03', subjectId: 'sub-3', subjectName: '计算机组成原理', questionsDone: 15, correctCount: 10, wrongCount: 5, duration: 45 },
  { id: 'sr-14', date: '2025-11-04', subjectId: 'sub-4', subjectName: '计算机网络', questionsDone: 22, correctCount: 19, wrongCount: 3, duration: 58 },
];

export const mockDashboardStats: DashboardStats = {
  totalQuestions: 690,
  totalWrong: 8,
  todayReview: 3,
  todayDone: 22,
  weekDone: 120,
  masteryRate: 0.85,
};

export const mockAnalyticsData: AnalyticsData = {
  dailyTrend: [
    { date: '2025-10-23', done: 15, correct: 12 },
    { date: '2025-10-24', done: 12, correct: 8 },
    { date: '2025-10-25', done: 30, correct: 22 },
    { date: '2025-10-26', done: 18, correct: 15 },
    { date: '2025-10-27', done: 22, correct: 18 },
    { date: '2025-10-28', done: 16, correct: 11 },
    { date: '2025-10-29', done: 14, correct: 9 },
    { date: '2025-10-30', done: 20, correct: 17 },
    { date: '2025-10-31', done: 25, correct: 20 },
    { date: '2025-11-01', done: 18, correct: 13 },
    { date: '2025-11-02', done: 30, correct: 24 },
    { date: '2025-11-03', done: 15, correct: 10 },
    { date: '2025-11-04', done: 22, correct: 19 },
    { date: '2025-11-05', done: 28, correct: 22 },
  ],
  wrongTrend: [
    { date: '2025-10-28', count: 1 },
    { date: '2025-10-29', count: 1 },
    { date: '2025-10-30', count: 0 },
    { date: '2025-10-31', count: 2 },
    { date: '2025-11-01', count: 2 },
    { date: '2025-11-02', count: 1 },
    { date: '2025-11-03', count: 1 },
    { date: '2025-11-04', count: 0 },
    { date: '2025-11-05', count: 2 },
  ],
  subjectAccuracy: [
    { subject: '数据结构', accuracy: 0.78 },
    { subject: '操作系统', accuracy: 0.72 },
    { subject: '计算机组成原理', accuracy: 0.68 },
    { subject: '计算机网络', accuracy: 0.81 },
  ],
};
